- name: Send SSApp.wsgi
  template: src="wsgi.j2" dest="/var/www/SSApp/{{app_version}}/SSApp.wsgi" mode=0644

- name: Apache2 enable mod_WSGI
  command: a2enmod wsgi

- name: Set Apache Environment Variables (1)
  lineinfile: dest=/etc/apache2/envvars state=present line='export AWS_ACCESS_KEY_ID={{aws_access_key}}'
  
- name: Set Apache Environment Variables (2)
  lineinfile: dest=/etc/apache2/envvars state=present line='export AWS_SECRET_ACCESS_KEY={{aws_secret_key}}'
  
- name: Set Apache Environment Variables (3)
  lineinfile: dest=/etc/apache2/envvars state=present line='export AWS_DEFAULT_REGION={{region}}'
